osx_image: xcode7.3
language: objective-c
xcode_workspace: ./code/engine/solutions/gkENGINE_xcode.xcworkspace
xcode_scheme: release_osx

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "K8ZEEAdspVjrD6mtO/4ozM1a5aRWwS8E06N5zsCjVEHm8f38atNxzK97W2gnSb/ySo2Z/dTM1JsJOZQ+638wHUhBBY0Zo2wgsnWwXICll6TJ1FagMs0+fahEChYONDt+X4C1frj/6VdoI7ypReBcRdHMwoIq+hbJ2eYL0FxaBF2y3hAEzdLbW2NDsYq3N4VEkCCHkXK2jPO5ygmcwSBzEqDCvYnpzP4f/mEzKL0wZQO/g/W8/AuTLIN02+PKfd40MOAiP6bvEyl0MSrSC0GzInl3MA3/caKQA4oZfzi5R2kI+qBqpSbhWWfr3A0mz/YRp6tOltWQHL96i1aKURCo+88t3unij3aZmiFOw+gei0Nt1jJm7C5csty67PbV2bO8u9R1+fh4TaWxXGvF175YS18lRWArgrBargw3x09g6vw4fJQne4i6D4C4OIs1uQIWesRZY2sGeqyY3ZEt0A0XcuTjQ6oAwAUjOKR6gFJz/vQxMXTA6FvWO+I+EZlH9hfwVv5fSzwyKyN8BF7wPI4HQqn8xLRpvZ6V/FDYXcmGMPfNPHv/kkURw3tpNygWiiU4WMy9yVDEpED0Hb5CrrF+VAD9EGzOViaRrnOnvMb3nk5QpJpSo2K44TmF/XN1dFe7PPz7NKUV7CxY5ZYr65uGmO0aM1Vm/u7TJoVT4qDbiKo="

addons:
  coverity_scan:
    project:
      name: "gameknife/gkEngine"
      description: "Build submitted via Travis CI"
    notification_email: kaimingyi@163.com
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan