osx_image: xcode7.3
language: objective-c
script: 
- sh travis_setup.sh
- xcodebuild -workspace ./code/engine/solutions/gkENGINE_xcode.xcworkspace -scheme release_osx

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "KYlPpSIe51RllNfX00Z25YdDDwrQglbRR+L/Suda/1EvZHhqRG9JouWXoIh4Wp8OxcAPAhqFLRdV83oVfHN04eZGMIRWZAuqyLPccBNcCjiqyxGyF2AYFT6MnAB9H73GxuqOtjZRovGHzumEFyS9BkJGUyU7p0ltk0Tldgrmb7vzqHiMouciAwXV0SFgtEicolWEmBYig7D/8e1HhLMjs9LQ9/NbHIbdLCo8DzXguhTeTRz6WU0RJcCuyh5iv1ov8ywtvXXQnkd5+wKfT8gTUHxGVCrgZjDn76RmrclTUn86rM93S/sth1NdJe+xcqEvQfUzsAiIgVxbeWojNvokKpTDHMJcu6wMENXPaGrGCUV71gq9PzrhKEAKrsOnrbA1EVPkmCQmYwQlObmNb91QbmRkZZUl9jnRDnf4hIcPXxUPKHr+49Ole+e5kQe/ZHI1DW9X7DwB1U/S3kcHnI+F0WTLN2LAk2DwnIZjLS4qO7lNHZaHsniCHBNpWCg671bn1hII/uAaNODoT+kXRfAXazRSYRwLZRZF5vbEa0Tv0cFkCtXenUu/FptwQMCKbtuBcp388n+Etr7mt7Huyhb7wLgh2bin7ay8GM4A9Noyter9J/elA8K90K40OE50joo5Z+LbNZwfx40YV1Oiao6OLxqGGnh+fC2zDh/iUVgMKOI="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "gameknife/gkEngine"
      description: "Build submitted via Travis CI"
    notification_email: kaimingyi@163.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan