os: Visual Studio 2015 CTP  
version: 0.1.{build}

configuration:
- DevelopLatest
#- Release

environment:
  matrix:
  - VS_VERSION: 14 2015
    VS_PLATFORM: win32
  - VS_VERSION: 14 2015
    VS_PLATFORM: x64

before_build:
- cmd: appveyor_setup.bat

build:
  project: c:\projects\gkengine\code\gkENGINE_Vc14.sln
  parallel: true
  verbosity: minimal
